import styled from "styled-components";

export const H1 = styled.h1``;
export const H2 = styled.h2``;
export const H3 = styled.h3``;
export const H4 = styled.h4``;
export const H5 = styled.h5``;
export const H6 = styled.h6``;
export const P = styled.p``;
export const Span = styled.span``;
export const Strong = styled.strong``;
export const Em = styled.em``;
export const Small = styled.small``;
export const B = styled.b``;
export const I = styled.i``;
export const U = styled.u``;
export const Sub = styled.sub``;
export const Sup = styled.sup``;
export const Code = styled.code``;
export const Pre = styled.pre``;
export const Kbd = styled.kbd``;
export const Samp = styled.samp``;
export const Var = styled.var``;
export const Mark = styled.mark``;
export const Time = styled.time``;
